# Generated by Django 4.1.7 on 2023-03-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_saleitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='No Description.', max_length=500),
        ),
    ]
